-- 01_sequences_and_identity.sql: sequences and IDENTITY columns.
--
-- Oracle source: dbhell.sql:52-58 exercises CREATE SEQUENCE with odd
-- increments, huge START values, MAXVALUE, NOCYCLE. Postgres supports the
-- same + IDENTITY columns (SQL-standard).

SET search_path = dbhell, public;

CREATE SEQUENCE test_seq_1;
CREATE SEQUENCE test_seq_2 START WITH 1000;
CREATE SEQUENCE test_seq_3 INCREMENT BY 37 START WITH 1000;

-- Quoted, space-containing identifier, bounded, NO CYCLE.
CREATE SEQUENCE "test seq 4" MAXVALUE 2 NO CYCLE;

-- bigint near the top of the range, Oracle's "really big MAXVALUE" was
-- 2e23 — Postgres bigint tops at 9223372036854775807, so we cap there.
CREATE SEQUENCE test_seq_5
    START WITH 9223372036854775806
    MAXVALUE  9223372036854775807
    INCREMENT BY 1
    NO CYCLE;

-- Cycling sequence with CACHE.
CREATE SEQUENCE test_seq_cycle
    START WITH 1
    MAXVALUE 5
    CYCLE
    CACHE 3;

-- IDENTITY column variants (SQL standard, Oracle 12c+).
CREATE TABLE identity_always (
    id     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    label  text
);

CREATE TABLE identity_default (
    id     bigint GENERATED BY DEFAULT AS IDENTITY
              (START WITH 100 INCREMENT BY 10) PRIMARY KEY,
    label  text
);

CREATE TABLE serial_legacy (
    id     serial PRIMARY KEY,
    label  text
);

INSERT INTO identity_always  (label) VALUES ('a'), ('b');
INSERT INTO identity_default (label) VALUES ('x');
INSERT INTO serial_legacy    (label) VALUES ('s1');
