
  CREATE TABLE OB_USAGE 
   (	RUN_DATE DATE NOT NULL ENABLE, 
	CLIENT_IP VARCHAR2(50 ) NOT NULL ENABLE, 
	ORACLE_DB_HOSTNAME VARCHAR2(50 ) NOT NULL ENABLE, 
	OS_USER_NAME VARCHAR2(80 ) NOT NULL ENABLE, 
	ORACLE_SID VARCHAR2(20 ) NOT NULL ENABLE, 
	ORACLE_USER_NAME VARCHAR2(30 ) NOT NULL ENABLE, 
	TARGET_ORACLE_VER VARCHAR2(10 ) NOT NULL ENABLE, 
	TARGET_JAVA_VER VARCHAR2(10 ) NOT NULL ENABLE, 
	PROC_COUNT NUMBER NOT NULL ENABLE, 
	SEQ_COUNT NUMBER NOT NULL ENABLE, 
	TABLE_COUNT NUMBER NOT NULL ENABLE, 
	SQL_COUNT NUMBER NOT NULL ENABLE, 
	IMPL_CLASS_NAME VARCHAR2(120 )
   ) ;
 